import type { Lesson } from "./lessons";

export const englishLessons: Lesson[] = [
  { char: "apple", pinyin: "/ˈæpəl/", icon: "🍎", title: "苹果", hint: "Apple 是红红的、甜甜的苹果。", sentence: "This is an apple." },
  { char: "banana", pinyin: "/bəˈnɑːnə/", icon: "🍌", title: "香蕉", hint: "Banana 是弯弯的黄色香蕉。", sentence: "I like bananas." },
  { char: "orange", pinyin: "/ˈɒrɪndʒ/", icon: "🍊", title: "橙子", hint: "Orange 是酸酸甜甜的橙子。", sentence: "The orange is round." },
  { char: "water", pinyin: "/ˈwɔːtər/", icon: "💧", title: "水", hint: "口渴的时候，我们要喝 water。", sentence: "I drink water." },
  { char: "milk", pinyin: "/mɪlk/", icon: "🥛", title: "牛奶", hint: "Milk 是白白的牛奶。", sentence: "The milk is white." },
  { char: "egg", pinyin: "/eɡ/", icon: "🥚", title: "鸡蛋", hint: "Egg 是圆圆的鸡蛋。", sentence: "I eat an egg." },
  { char: "cat", pinyin: "/kæt/", icon: "🐱", title: "猫", hint: "Cat 是会喵喵叫的小猫。", sentence: "The cat is cute." },
  { char: "dog", pinyin: "/dɒɡ/", icon: "🐶", title: "狗", hint: "Dog 是会汪汪叫的小狗。", sentence: "I see a dog." },
  { char: "bird", pinyin: "/bɜːrd/", icon: "🐦", title: "鸟", hint: "Bird 是会在天空飞的小鸟。", sentence: "The bird can fly." },
  { char: "fish", pinyin: "/fɪʃ/", icon: "🐟", title: "鱼", hint: "Fish 是在水里游的小鱼。", sentence: "The fish can swim." },
  { char: "duck", pinyin: "/dʌk/", icon: "🦆", title: "鸭子", hint: "Duck 是扁嘴巴的小鸭子。", sentence: "The duck is yellow." },
  { char: "rabbit", pinyin: "/ˈræbɪt/", icon: "🐰", title: "兔子", hint: "Rabbit 是有长耳朵的小兔子。", sentence: "The rabbit can jump." },
  { char: "bear", pinyin: "/beər/", icon: "🐻", title: "熊", hint: "Bear 是大大的熊。", sentence: "The bear is big." },
  { char: "sun", pinyin: "/sʌn/", icon: "☀️", title: "太阳", hint: "Sun 是天空中明亮的太阳。", sentence: "The sun is warm." },
  { char: "moon", pinyin: "/muːn/", icon: "🌙", title: "月亮", hint: "Moon 是夜空中的月亮。", sentence: "I see the moon." },
  { char: "star", pinyin: "/stɑːr/", icon: "⭐", title: "星星", hint: "Star 是夜空中闪亮的星星。", sentence: "The star is bright." },
  { char: "rain", pinyin: "/reɪn/", icon: "🌧️", title: "雨", hint: "Rain 是从云朵落下的小雨滴。", sentence: "I like the rain." },
  { char: "tree", pinyin: "/triː/", icon: "🌳", title: "树", hint: "Tree 是有树干和树叶的大树。", sentence: "The tree is green." },
  { char: "flower", pinyin: "/ˈflaʊər/", icon: "🌸", title: "花", hint: "Flower 是香香的、美丽的花。", sentence: "This flower is pink." },
  { char: "red", pinyin: "/red/", icon: "🔴", title: "红色", hint: "Red 是苹果常见的颜色。", sentence: "The apple is red." },
  { char: "yellow", pinyin: "/ˈjeləʊ/", icon: "🟡", title: "黄色", hint: "Yellow 是香蕉常见的颜色。", sentence: "The banana is yellow." },
  { char: "blue", pinyin: "/bluː/", icon: "🔵", title: "蓝色", hint: "Blue 是晴朗天空的颜色。", sentence: "The sky is blue." },
  { char: "green", pinyin: "/ɡriːn/", icon: "🟢", title: "绿色", hint: "Green 是小草和树叶的颜色。", sentence: "The leaf is green." },
  { char: "one", pinyin: "/wʌn/", icon: "1️⃣", title: "一", hint: "One 就是数字一。", sentence: "I have one ball." },
  { char: "two", pinyin: "/tuː/", icon: "2️⃣", title: "二", hint: "Two 就是数字二。", sentence: "I see two cats." },
  { char: "three", pinyin: "/θriː/", icon: "3️⃣", title: "三", hint: "Three 就是数字三。", sentence: "I have three toys." },
  { char: "hand", pinyin: "/hænd/", icon: "✋", title: "手", hint: "Hand 是我们能干的小手。", sentence: "Clap your hands." },
  { char: "eye", pinyin: "/aɪ/", icon: "👁️", title: "眼睛", hint: "Eye 是帮助我们看东西的眼睛。", sentence: "I have two eyes." },
  { char: "nose", pinyin: "/nəʊz/", icon: "👃", title: "鼻子", hint: "Nose 是能闻到香味的鼻子。", sentence: "Touch your nose." },
  { char: "book", pinyin: "/bʊk/", icon: "📖", title: "书", hint: "Book 是有图画和故事的书。", sentence: "I read a book." },
  { char: "ball", pinyin: "/bɔːl/", icon: "⚽", title: "球", hint: "Ball 是会滚动、会弹跳的球。", sentence: "This is my ball." },
  { char: "car", pinyin: "/kɑːr/", icon: "🚗", title: "汽车", hint: "Car 是有轮子的小汽车。", sentence: "The car is fast." },
  { char: "home", pinyin: "/həʊm/", icon: "🏠", title: "家", hint: "Home 是温暖的家。", sentence: "I am at home." },
  { char: "hello", pinyin: "/həˈləʊ/", icon: "👋", title: "你好", hint: "见到别人时，可以开心地说 hello。", sentence: "Hello, my friend!" },
  { char: "happy", pinyin: "/ˈhæpi/", icon: "😄", title: "开心", hint: "Happy 是高兴、开心的感觉。", sentence: "I am happy." },
  { char: "love", pinyin: "/lʌv/", icon: "❤️", title: "爱", hint: "Love 是关心、陪伴和暖暖的拥抱。", sentence: "I love my family." },
];
